spring:
  application:
    name: real_estate_backend
  datasource:
    url: jdbc:postgresql://localhost:5432/cleancode
    username: cleancode
    password: cleancode
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

application:
  security:
    jwt:
      expiration: 86400000 # a day
      secret: 67d4ba3566b80796c10f6141e0a4509b19a4e0bc7a97768f24cb24233946069a
      refresh-token:
        expiration: 604800000 # 7 days

photo:
  upload:
    dir: /tmp/real-estate/images